#!/usr/bin/python

from sys import argv
import os
from libxml import BuildXml

VERSION = '1.0.1.1'

if argv[1] != '--' and 0 != argv[1].find("--") :
	if len(argv) < 2 :
		print """Not enough parameters !
use -- help for more informations"""
        else:
		global cmdline
		if argv[1].find(".xml") != '-1':
			if len(argv) == 3 :
				cmdline = ("ant -buildfile %s %s") % (argv[1],argv[2])	
			else:
				xml = BuildXml(argv[1])
				xml.getProject()
				if not xml.target:
					print "Error : xml file " + argv[1] + " have no target !"
					exit()
	                        cmdline = ("ant -buildfile %s %s") % (argv[1],xml.target)
			os.system( cmdline )
			desc = xml.getDest()
			cmdline = ("minjs.py %s %s") % (desc,desc)
			#lib =  os.path.dirname(__file__) +  "/lib/yuicompressor-2.4.2.jar"
			#cmdline = ("java -jar %s --type js --charset utf-8 -o %s %s") % ( lib,desc,desc )
			os.system( cmdline )
			print "done!"
else:
	global operation 
        operation = argv[1]
	if len(argv)>2 :
           operation = operation + argv[2]
	if operation == '--help' or operation == 'help':
		print "help information"
	elif operation == '--version' or operation == 'version':
		print ("PackJs version %s by darrel ") % (VERSION)
		os.system("ant -version")
        else:
		print ("Unknow operation %s \nuser --help for more information") % (operation)
