#!/usr/bin/python

from sys import argv
import os
import re

VERSION = '1.0.0.1'
if argv[1] != '--' and 0 != argv[1].find("--") :
	if len(argv) < 2 :
		print """Not enough parameters !
use -- help for more informations"""
        else:
		global cmdline
		if argv[1].find(".xml") != '-1':
			if len(argv) == 3 :
				cmdline = ("ant -buildfile %s %s") % (argv[1],argv[2])	
			else:
	                        cmdline = ("ant -buildfile %s ") % (argv[1])
			os.system(cmdline)
else:
	global operation 
        operation = argv[1]
	if len(argv)>2 :
           operation = operation + argv[2]
	if operation == '--help' or operation == 'help':
		print "help information"
	elif operation == '--version' or operation == 'version':
		print ("PackJs version %s by darrel ") % (VERSION)
		os.system("ant -version")
        else:
		print ("Unknow operation %s \nuser --help for more information") % (operation)
